apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mongo-express
  namespace: playground
spec:
  rules:
  - host: mongo-express.com
    http:
      paths:
      - backend:
          serviceName: mongo-express-service
          servicePort: 8081
