apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mongo-express
  namespace: playground
spec:
  rules:
  - host: mongoexpress.com
    http:
      paths:
      - path: /v1
        backend:
          serviceName: mongo-express-service
          servicePort: 8081
